apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: <your-dockerhub-username>/product-app:latest
          ports:
            - containerPort: 8001