apiVersion: apps/v1
kind: Deployment 
metadata:
  name:
spec:
  replicas: 1
  selector:
    matchLabels :
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
       - name: user
         image:
         ports:
            -containerPort: 8000